// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Manuel d\'utilisation', // Name of the category in the sidebar
      collapsed: false, // You can set this to 'true' if you want the category to be collapsed initially
      items: [
        'guide-utilisateur/preambule',
        'guide-utilisateur/avant-de-demarrer', 
        'guide-utilisateur/accueil', // Link to the .md file (without extension)
        'guide-utilisateur/onglet-station',     // Link to another .md file
        'guide-utilisateur/onglet-campagne', 
        'guide-utilisateur/onglet-chargement', 
        'guide-utilisateur/onglet-qualification',   
        'guide-utilisateur/onglet-valid-qualif', 
        'guide-utilisateur/onglet-synthese',   // Add more files as needed
      ],
    },
  ],
};
export default sidebars;
